/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Database;

/**
 *
 * @author Nadine Azhalia
 */
public class InputPegawai extends javax.swing.JFrame implements View{

    /**
     * Creates new form InputPegawai
     */
    public InputPegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAlamat = new javax.swing.JTextArea();
        tfNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNoKtp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfGaji = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        cbPosisi = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(142, 0, 0));
        jLabel2.setText("Rp.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 30, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(142, 0, 0));
        jLabel3.setText("Nama   :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(142, 0, 0));
        jLabel4.setText("Alamat :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(142, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Citramart");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrasi Pegawai");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 110));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Backbtn.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 80, 30));

        tfAlamat.setColumns(20);
        tfAlamat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tfAlamat.setForeground(new java.awt.Color(51, 51, 51));
        tfAlamat.setRows(5);
        tfAlamat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(tfAlamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 190, 120));

        tfNama.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfNama.setForeground(new java.awt.Color(51, 51, 51));
        tfNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        jPanel1.add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 190, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(142, 0, 0));
        jLabel7.setText("No. KTP :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(142, 0, 0));
        jLabel8.setText("No. KTP");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(142, 0, 0));
        jLabel9.setText("Gaji            :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 100, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(142, 0, 0));
        jLabel10.setText("Username :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 110, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(142, 0, 0));
        jLabel11.setText("Password   :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(142, 0, 0));
        jLabel12.setText("E-mail         :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 150, -1));

        tfNoKtp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfNoKtp.setForeground(new java.awt.Color(51, 51, 51));
        tfNoKtp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfNoKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoKtpActionPerformed(evt);
            }
        });
        jPanel1.add(tfNoKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, 20));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(142, 0, 0));
        jLabel13.setText("Posisi           :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 150, -1));

        tfGaji.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfGaji.setForeground(new java.awt.Color(51, 51, 51));
        tfGaji.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGajiActionPerformed(evt);
            }
        });
        jPanel1.add(tfGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 130, 20));

        tfUsername.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(51, 51, 51));
        tfUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 160, 20));

        tfEmail.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(51, 51, 51));
        tfEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        jPanel1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 160, 20));

        tfPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 160, 20));

        cbPosisi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbPosisi.setForeground(new java.awt.Color(142, 0, 0));
        cbPosisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Koordinator", "Kasir", "Pegawai Gudang" }));
        cbPosisi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        cbPosisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPosisiActionPerformed(evt);
            }
        });
        jPanel1.add(cbPosisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 150, 20));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/submit.png"))); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfNoKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoKtpActionPerformed

    private void tfGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGajiActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void cbPosisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPosisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPosisiActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        String noktp = tfNoKtp.getText();
                String nama = tfNama.getText();
                String alamat = tfAlamat.getText();
                String gaji = tfGaji.getText();
                String username = tfUsername.getText();
                String password = tfPassword.getText();
                String email = tfEmail.getText();
                String posisi = cbPosisi.getItemAt(cbPosisi
                        .getSelectedIndex());
                System.out.println(posisi);
                
                try {
                    String query = "INSERT INTO user VALUES ('"
                        + username + "', '" 
                        + password + "', '" + nama + "', '"
                        + email + "', '" 
                        + posisi + "', " + gaji + ", '" + noktp
                        + "', '" 
                        + alamat 
                        + "')";
                    Database.getInstance().getStatement().executeUpdate(query);
                    showMessage("Data pegawai berhasil diinput");
                } catch (SQLException ex) {
                    showMessage("Username telah digunakan");
                }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbPosisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tfAlamat;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfGaji;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoKtp;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnBack.addActionListener(e);
        btnSubmit.addActionListener(e);
    }

    @Override
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public void setBtnBack(JButton btnBack) {
        this.btnBack = btnBack;
    }
    
    public JButton getBtnSubmit() {
        return btnBack;
    }

    public void setBtnSubmit(JButton btnSubmit) {
        this.btnBack = btnSubmit;
    }

    public JComboBox<String> getCbPosisi() {
        return cbPosisi;
    }

    public void setCbPosisi(JComboBox<String> cbPosisi) {
        this.cbPosisi = cbPosisi;
    }

    public JTextArea getTfAlamat() {
        return tfAlamat;
    }

    public void setTfAlamat(JTextArea tfAlamat) {
        this.tfAlamat = tfAlamat;
    }

    public JTextField getTfEmail() {
        return tfEmail;
    }

    public void setTfEmail(JTextField tfEmail) {
        this.tfEmail = tfEmail;
    }

    public JTextField getTfGaji() {
        return tfGaji;
    }

    public void setTfGaji(JTextField tfGaji) {
        this.tfGaji = tfGaji;
    }

    public JTextField getTfNama() {
        return tfNama;
    }

    public void setTfNama(JTextField tfNama) {
        this.tfNama = tfNama;
    }

    public JTextField getTfNoKtp() {
        return tfNoKtp;
    }

    public void setTfNoKtp(JTextField tfNoKtp) {
        this.tfNoKtp = tfNoKtp;
    }

    public JPasswordField getTfPassword() {
        return tfPassword;
    }

    public void setTfPassword(JPasswordField tfPassword) {
        this.tfPassword = tfPassword;
    }

    public JTextField getTfUsername() {
        return tfUsername;
    }

    public void setTfUsername(JTextField tfUsername) {
        this.tfUsername = tfUsername;
    }
    
    
}
