/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Nadine Azhalia
 */
public class MainManajer extends javax.swing.JFrame implements View{

    /**
     * Creates new form MainManajer
     */
    public MainManajer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDataPegawai = new javax.swing.JButton();
        btnDataLaporan = new javax.swing.JButton();
        btnRegistrasi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(142, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Manajer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 80, 174, 31);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Citramart");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(414, 21, 166, 45);

        btnDataPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/team.png"))); // NOI18N
        btnDataPegawai.setBorder(null);
        btnDataPegawai.setBorderPainted(false);
        btnDataPegawai.setContentAreaFilled(false);
        jPanel1.add(btnDataPegawai);
        btnDataPegawai.setBounds(260, 140, 120, 130);

        btnDataLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/seo-report.png"))); // NOI18N
        btnDataLaporan.setBorder(null);
        btnDataLaporan.setBorderPainted(false);
        btnDataLaporan.setContentAreaFilled(false);
        btnDataLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataLaporanActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataLaporan);
        btnDataLaporan.setBounds(70, 150, 130, 130);

        btnRegistrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add-user.png"))); // NOI18N
        btnRegistrasi.setBorderPainted(false);
        btnRegistrasi.setContentAreaFilled(false);
        btnRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrasi);
        btnRegistrasi.setBounds(450, 150, 140, 130);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Pegawai");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 280, 106, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrasi Pegawai");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 280, 140, 20);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data Laporan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 280, 110, 20);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logout.png"))); // NOI18N
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        jPanel1.add(btnLogout);
        btnLogout.setBounds(450, 340, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataLaporanActionPerformed

    private void btnRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainManajer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataLaporan;
    private javax.swing.JButton btnDataPegawai;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegistrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnDataLaporan.addActionListener(e);
        btnDataPegawai.addActionListener(e);
        btnLogout.addActionListener(e);
        btnRegistrasi.addActionListener(e);
    }

    @Override
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public JButton getBtnDataLaporan() {
        return btnDataLaporan;
    }

    public void setBtnDataLaporan(JButton btnDataLaporan) {
        this.btnDataLaporan = btnDataLaporan;
    }

    public JButton getBtnDataPegawai() {
        return btnDataPegawai;
    }

    public void setBtnDataPegawai(JButton btnDataPegawai) {
        this.btnDataPegawai = btnDataPegawai;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public void setBtnLogout(JButton btnLogout) {
        this.btnLogout = btnLogout;
    }

    public JButton getBtnRegistrasi() {
        return btnRegistrasi;
    }

    public void setBtnRegistrasi(JButton btnRegistrasi) {
        this.btnRegistrasi = btnRegistrasi;
    }
    
    
}
