/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Database;

/**
 *
 * @author Nadine Azhalia
 */
public class MenuKoordinator extends javax.swing.JFrame implements View {

    /**
     * Creates new form MainKoor
     */
    public MenuKoordinator() {
        initComponents();
        Date date= new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        System.out.println(month);
        System.out.println(year);
        
        try{
            String query = "SELECT * FROM laporan WHERE MONTH(tanggal) = " + month + " AND YEAR(tanggal) = " + year;
            Statement statement = Database.getInstance().getStatement();
            ResultSet rs = statement.executeQuery(query);
            if (!rs.next()){
                lbNotif.setText("<html>Anda belum membuat<br>laporan untuk bulan lalu!<html>");
            }
            else{
                lbNotif.setText("<html>Halo, Koordinator<br>Citramart!:)<html>");
            }
        }
        catch (SQLException e){
            throw new IllegalArgumentException("Error for notifications!");
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        btnPengeluaran = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lbNotif = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(142, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Koordinator");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 90, 213, 31);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Citramart");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(414, 21, 166, 45);

        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/folder.png"))); // NOI18N
        btnLaporan.setBorder(null);
        btnLaporan.setBorderPainted(false);
        btnLaporan.setContentAreaFilled(false);
        jPanel1.add(btnLaporan);
        btnLaporan.setBounds(230, 140, 135, 137);

        btnPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/trolley.png"))); // NOI18N
        btnPemesanan.setBorder(null);
        btnPemesanan.setBorderPainted(false);
        btnPemesanan.setContentAreaFilled(false);
        jPanel1.add(btnPemesanan);
        btnPemesanan.setBounds(50, 140, 130, 130);

        btnPengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pie-chart.png"))); // NOI18N
        btnPengeluaran.setBorderPainted(false);
        btnPengeluaran.setContentAreaFilled(false);
        jPanel1.add(btnPengeluaran);
        btnPengeluaran.setBounds(420, 140, 140, 130);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Laporan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 280, 61, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pengeluaran Operasional");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 280, 187, 20);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pemesanan Barang");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 280, 143, 20);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logout.png"))); // NOI18N
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        jPanel1.add(btnLogout);
        btnLogout.setBounds(480, 350, 90, 30);

        lbNotif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNotif.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbNotif);
        lbNotif.setBounds(20, 40, 180, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Notifikasi!");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 20, 80, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuKoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuKoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuKoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuKoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuKoordinator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNotif;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnLaporan.addActionListener(e);
        btnLogout.addActionListener(e);
        btnPemesanan.addActionListener(e);
        btnPengeluaran.addActionListener(e);
    }

    @Override
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public JButton getBtnLaporan() {
        return btnLaporan;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnPemesanan() {
        return btnPemesanan;
    }

    public JButton getBtnPengeluaran() {
        return btnPengeluaran;
    }
    
    
}
