/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.Database;
import model.Kasir;
import model.Session;

/**
 *
 * @author Nadine Azhalia
 */
public class Transaksi extends javax.swing.JFrame implements View{
    public Transaksi() {
        initComponents();
        this.setSize(650, 550);
        tfKasir.setEditable(false);
        tfKembali.setEditable(false);
        tfTanggal.setEditable(false);
        tfNoTransaksi.setEditable(false);
        tfTotalHarga.setEditable(false);
        tfTotalHarga.setText("0");            
        tfKasir.setText(Session.getPegawai().getName());
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
//        Calendar cal = Calendar.getInstance();
//        tfTanggal.setText(dateFormat.format(cal));

        Date date = new Date();
        System.out.println(dateFormat.format(date));
        tfTanggal.setText(dateFormat.format(date));

        try {
            ResultSet rs = Database.getInstance().getStatement().executeQuery("SELECT MAX(id_transaksi) AS no_trk FROM transaksi");
            rs.next();
            tfNoTransaksi.setText(String.valueOf(rs.getInt("no_trk")+1));
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        tfBayar.getDocument().addDocumentListener(new DocumentListener() {
//            @Override
//            public void changedUpdate(DocumentEvent e) {
//              warn();
//            }
//            @Override
//            public void removeUpdate(DocumentEvent e) {
//              warn();
//            }
//            @Override
//            public void insertUpdate(DocumentEvent e) {
//              warn();
//            }
//
//            public void warn() {
//                if (Integer.parseInt(tfBayar.getText()) == 0){
//                    tfBayar.setText("0");
//                }
//                int jml = Integer.parseInt(tfBayar.getText()) - Integer.parseInt(tfTotalHarga.getText());
//                tfKembali.setText(String.valueOf(jml)); 
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNoTransaksi = new javax.swing.JTextField();
        tfTanggal = new javax.swing.JTextField();
        tfBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfKembali = new javax.swing.JTextField();
        tfTotalHarga = new javax.swing.JTextField();
        tfKasir = new javax.swing.JTextField();
        tfKodeBarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTranksaksi = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(142, 0, 0));
        jLabel12.setText("Rp.");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(142, 0, 0));
        jLabel2.setText("No. Transaksi");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(142, 0, 0));
        jLabel3.setText("Tanggal, Waktu");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(142, 0, 0));
        jLabel4.setText("Kode Barang ");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(142, 0, 0));
        jLabel5.setText("Kasir");

        jPanel2.setBackground(new java.awt.Color(142, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Citramart");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jalan Terusan Buah Batu, Telkom University");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tfNoTransaksi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfNoTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        tfNoTransaksi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfNoTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoTransaksiActionPerformed(evt);
            }
        });

        tfTanggal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfTanggal.setForeground(new java.awt.Color(51, 51, 51));
        tfTanggal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));

        tfBayar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfBayar.setForeground(new java.awt.Color(51, 51, 51));
        tfBayar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfBayar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfBayarPropertyChange(evt);
            }
        });
        tfBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBayarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBayarKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(142, 0, 0));
        jLabel7.setText("Total Harga");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(142, 0, 0));
        jLabel8.setText("Bayar");

        tfKembali.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfKembali.setForeground(new java.awt.Color(51, 51, 51));
        tfKembali.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));

        tfTotalHarga.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfTotalHarga.setForeground(new java.awt.Color(51, 51, 51));
        tfTotalHarga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalHargaActionPerformed(evt);
            }
        });

        tfKasir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfKasir.setForeground(new java.awt.Color(51, 51, 51));
        tfKasir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));

        tfKodeBarang.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfKodeBarang.setForeground(new java.awt.Color(51, 51, 51));
        tfKodeBarang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 0, 0), 1, true));
        tfKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodeBarangActionPerformed(evt);
            }
        });
        tfKodeBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKodeBarangKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(142, 0, 0));
        jLabel10.setText("Kembali");

        tableTranksaksi.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tableTranksaksi.setForeground(new java.awt.Color(142, 0, 0));
        tableTranksaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Kode Barang", "Nama Barang", "Jumlah", "Harga", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTranksaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableTranksaksiKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableTranksaksi);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/submit.png"))); // NOI18N
        btnOk.setBorder(null);
        btnOk.setBorderPainted(false);
        btnOk.setContentAreaFilled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Backbtn.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(142, 0, 0));
        jLabel9.setText("Rp.");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(142, 0, 0));
        jLabel11.setText("Rp.");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(142, 0, 0));
        jLabel13.setText("Rp.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNoTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(tfTanggal)
                            .addComponent(tfKasir))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfBayar)
                            .addComponent(tfTotalHarga)
                            .addComponent(tfKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tfKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(tfKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNoTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoTransaksiActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    private void tfTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalHargaActionPerformed

    private void tfBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBayarKeyTyped
        // TODO add your handling code here:
//        int jml = Integer.parseInt(tfBayar.getText()) - Integer.parseInt(tfTotalHarga.getText());
//        tfKembali.setText(String.valueOf(jml));
    }//GEN-LAST:event_tfBayarKeyTyped

    private void tfBayarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfBayarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBayarPropertyChange

    private void tfKodeBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKodeBarangKeyPressed
        // TODO add your handling code here:
        DefaultTableModel table_transaksi = (DefaultTableModel) tableTranksaksi.getModel();
        // Check data exist
        if (evt.getKeyChar() == KeyEvent.VK_ENTER){
            String barcode = tfKodeBarang.getText();
            boolean foundItem = false;
            for (int i=0; i<table_transaksi.getRowCount(); i++){
                if (barcode.equals(table_transaksi.getValueAt(i, 1).toString())){
                    foundItem = true;
                    table_transaksi.setValueAt(Integer.parseInt(table_transaksi.getValueAt(i, 3).toString())+1, i, 3);
                    long jml_harga = Long.parseLong(table_transaksi.getValueAt(i, 3).toString()) * Long.parseLong(table_transaksi.getValueAt(i, 4).toString());
                    table_transaksi.setValueAt(jml_harga, i, 5);
                    break;
                }
            }
            if (!foundItem){
                try {
                    Kasir kas = (Kasir) Session.getPegawai();
                    ResultSet rs = kas.scanBarcode(barcode);
                    if (rs.next()){
                        long harga = rs.getLong("harga_jual");
                        table_transaksi.addRow(new Object[]{table_transaksi.getRowCount()+1,rs.getString("barcode"), rs.getString("nama"), 1, rs.getInt("harga_jual"), harga});
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Kode barang tidak ditemukan!");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Kode barang tidak ditemukan!");
                }
            }
            tfKodeBarang.setText("");
            int total_harga = 0;
            for (int i=0; i<table_transaksi.getRowCount(); i++){
                total_harga += Integer.valueOf(table_transaksi.getValueAt(i, 5).toString());
            }
            tfTotalHarga.setText(String.valueOf(total_harga));
        }
        
    }//GEN-LAST:event_tfKodeBarangKeyPressed

    private void tfKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKodeBarangActionPerformed

    private void tfBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBayarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int jml = Integer.parseInt(tfBayar.getText()) - Integer.parseInt(tfTotalHarga.getText());
            tfKembali.setText(String.valueOf(jml)); 
        }
    }//GEN-LAST:event_tfBayarKeyPressed

    private void tableTranksaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableTranksaksiKeyPressed
        // TODO add your handling code here:
        DefaultTableModel table_transaksi = (DefaultTableModel) tableTranksaksi.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int row = tableTranksaksi.getSelectedRow();
            long jml = Long.parseLong(table_transaksi.getValueAt(row, 3).toString()) * Long.parseLong(table_transaksi.getValueAt(row, 4).toString());
            table_transaksi.setValueAt(jml, row, 5);
            long total_harga = 0;
            for (int i=0; i<table_transaksi.getRowCount(); i++){
                total_harga += Long.parseLong(table_transaksi.getValueAt(i, 3).toString()) * Long.parseLong(table_transaksi.getValueAt(i, 4).toString());
            }
            tfTotalHarga.setText(String.valueOf(total_harga));
        }
    }//GEN-LAST:event_tableTranksaksiKeyPressed

    public JButton getBtnBack() {
        return btnBack;
    }

    public void setBtnBack(JButton btnBack) {
        this.btnBack = btnBack;
    }

    public JButton getBtnOk() {
        return btnOk;
    }

    public void setBtnOk(JButton btnOk) {
        this.btnOk = btnOk;
    }

    public JTable getTableTranksaksi() {
        return tableTranksaksi;
    }

    public void setTableTranksaksi(JTable tableTranksaksi) {
        this.tableTranksaksi = tableTranksaksi;
    }

    public JTextField getTfBayar() {
        return tfBayar;
    }

    public void setTfBayar(JTextField tfBayar) {
        this.tfBayar = tfBayar;
    }

    public JTextField getTfKasir() {
        return tfKasir;
    }

    public void setTfKasir(JTextField tfKasir) {
        this.tfKasir = tfKasir;
    }

    public JTextField getTfKembali() {
        return tfKembali;
    }

    public void setTfKembali(JTextField tfKembali) {
        this.tfKembali = tfKembali;
    }

    public JTextField getTfKodeBarang() {
        return tfKodeBarang;
    }

    public void setTfKodeBarang(JTextField tfKodeBarang) {
        this.tfKodeBarang = tfKodeBarang;
    }

    public JTextField getTfNoTransaksi() {
        return tfNoTransaksi;
    }

    public void setTfNoTransaksi(JTextField tfNoTransaksi) {
        this.tfNoTransaksi = tfNoTransaksi;
    }

    public JTextField getTfTanggal() {
        return tfTanggal;
    }

    public void setTfTanggal(JTextField tfTanggal) {
        this.tfTanggal = tfTanggal;
    }

    public JTextField getTfTotalHarga() {
        return tfTotalHarga;
    }

    public void setTfTotalHarga(JTextField tfTotalHarga) {
        this.tfTotalHarga = tfTotalHarga;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTranksaksi;
    private javax.swing.JTextField tfBayar;
    private javax.swing.JTextField tfKasir;
    private javax.swing.JTextField tfKembali;
    private javax.swing.JTextField tfKodeBarang;
    private javax.swing.JTextField tfNoTransaksi;
    private javax.swing.JTextField tfTanggal;
    private javax.swing.JTextField tfTotalHarga;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnOk.addActionListener(e);
        btnBack.addActionListener(e);
    }

    @Override
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    public void updateTrk(){
        try {
            ResultSet rs = Database.getInstance().getStatement().executeQuery("SELECT MAX(id_transaksi) AS no_trk FROM transaksi");
            rs.next();
            tfNoTransaksi.setText(String.valueOf(rs.getInt("no_trk")+1));
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
//        Calendar cal = Calendar.getInstance();
//        tfTanggal.setText(dateFormat.format(cal));

        Date date = new Date();
        System.out.println(dateFormat.format(date));
        tfTanggal.setText(dateFormat.format(date));

    }
}
